//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencija
    {
        public int id_loga { get; set; }

        public int id_uredaj_korisnika { get; set; }
        public System.DateTime datum { get; set; }
        public bool aktivan { get; set; }
        public int id_recepta { get; set; }
    
        public virtual recepti recepti { get; set; }

        public virtual uredaj_korisnici uredaj_korisnici { get; set; }
    }
}
