//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recepti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recepti()
        {
            this.recepti_akcije = new HashSet<recepti_akcije>();
            this.evidencija = new HashSet<evidencija>();
        }

        public int id_recepta { get; set; }
        public string naziv { get; set; }
        public Nullable<int> id_korisnika { get; set; }
        public Nullable<System.DateTime> datum { get; set; }

        public virtual korisnici korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepti_akcije> recepti_akcije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencija> evidencija { get; set; }
    }
}
