//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recepti_akcije
    {
        public int id_recepta { get; set; }
        public int id_tipa_loga { get; set; }
        public int id { get; set; }
    
        public virtual recepti recepti { get; set; }
        public virtual tipovi_evidnecije tipovi_evidnecije { get; set; }
    }
}
