//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class uredaji
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uredaji()
        {
            this.uredaj_korisnici = new HashSet<uredaj_korisnici>();
        }
    
        public int id_uredaja { get; set; }
        public int id_tipa { get; set; }
        public string uniqe_code { get; set; }
    
        public virtual tipovi_uredaja tipovi_uredaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uredaj_korisnici> uredaj_korisnici { get; set; }

    }
}
