//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class uredaj_korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uredaj_korisnici()
        {
            this.evidencija = new HashSet<evidencija>();

        }
    
        public int id_uredaja_korisnika { get; set; }
        public Nullable<int> id_korisnika { get; set; }
        public Nullable<int> id_uredaja { get; set; }
        public Nullable<System.DateTime> datum_registracije_uredaja { get; set; }

        public string naziv_uredaja { get; set; }
        public string ip { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual uredaji uredaji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencija> evidencija { get; set; }

    }
}
